platform :osx, '10.10'

# Ignore all warnings from all pods
inhibit_all_warnings!

# Use frameworks for Swift
use_frameworks!

target 'RocksPodmacOS' do
  pod 'ObjectiveRocks', git: 'git@github.com:rob-keepsafe/ObjectiveRocks', branch: 'fix/podspec', :submodules => true
end